export const movie = [
  {
    id: 1,
    title: 'Inception',
    description: 'A mind-bending thriller by Christopher Nolan.',
    image: 'https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg',
    language: 'English',
    release_date: '2010-07-16',
    vote_average: 8.8,
    runtime: 148,
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
  }, 
  {
    id: 2,
    title: 'Parasite',
    description: 'A dark comedy thriller by Bong Joon-ho.',
    image: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    language: 'Korean',
    release_date: '2019-05-30',
    vote_average: 8.6,
    runtime: 132,
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
  },
  {
    id: 3,
    title: 'Spirited Away',
    description: 'A fantasy adventure by Hayao Miyazaki.',
    image: 'https://image.tmdb.org/t/p/w500/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg',
    language: 'Japanese',
    release_date: '2001-07-20',
    vote_average: 8.5,
    runtime: 125,
    overview: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
  },
  // Add more movies as needed
];